In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('/Users/barry/CodeAcademy/Ideal_dataset/combined_houses/6_months_data.csv')

In [29]:
df.time = pd.to_datetime(df.time)
df.index= df.time

In [30]:
df= df.drop(columns=['electric-combined-next-hour'], axis=1)

In [31]:
resampled_df = df.resample('3H')
resampled_df = resampled_df.agg({
    'temperature_2m (°C)': 'mean',
    'relative_humidity_2m (%)': 'mean',
    'weather_code (wmo code)': 'first',
    'wind_speed_10m (km/h)': 'mean',
    'wind_direction_10m (°)': 'mean',
    'day': 'first',
    'hour': 'first',
    'electric-combined': 'sum',
    'electric-combined-yesterday': 'sum',
    'electric-combined-last-week': 'sum',

})

/var/folders/ch/cdbcz7115ms5zvq6n9ds4wn00000gn/T/ipykernel_49969/2726307218.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_df = df.resample('3H')

In [32]:
resampled_df['electric-combined_3H-forecast']= resampled_df['electric-combined'].shift(-1)

In [33]:
resampled_df.reset_index()

,time,temperature_2m (°C),relative_humidity_2m (%),weather_code (wmo code),wind_speed_10m (km/h),wind_direction_10m (°),day,hour,electric-combined,electric-combined-yesterday,electric-combined-last-week,electric-combined_3H-forecast
0,2017-09-01 00:00:00,10.465306,89.469388,0,8.348980,253.976190,4.0,0.0,9736.94,0.00,0.00,11199.00
1,2017-09-01 03:00:00,9.292857,91.877551,1,5.606803,236.513605,4.0,3.0,11199.00,0.00,0.00,18686.89
2,2017-09-01 06:00:00,11.101701,87.887755,3,3.805442,236.986395,4.0,6.0,18686.89,0.00,0.00,19569.85
3,2017-09-01 09:00:00,13.079252,81.112245,3,5.465986,159.707483,4.0,9.0,19569.85,0.00,0.00,16771.05
4,2017-09-01 12:00:00,14.598007,76.567821,2,8.024672,54.914829,4.0,12.0,16771.05,0.00,0.00,21973.35
...,...,...,...,...,...,...,...,...,...,...,...,...
1443,2018-02-28 09:00:00,-2.306763,67.632850,71,24.453019,88.538647,2.0,9.0,63019.70,46480.32,42101.31,37406.73
1444,2018-02-28 12:00:00,-3.267633,80.420290,73,25.190821,68.531401,2.0,13.0,37406.73,18940.44,21831.77,55062.09
1445,2018-02-28 15:00:00,-3.782126,76.207729,71,21.245733,87.867955,2.0,15.0,55062.09,41115.62,34962.11,78467.42
1446,2018-02-28 18:00:00,-4.502254,78.454106,2,17.934300,77.238325,2.0,18.0,78467.42,59224.35,61831.36,45810.78
1447,2018-02-28 21:00:00,-4.142834,76.628019,71,20.369565,85.312399,2.0,21.0,45810.78,51317.40,40919.70,NaN

In [34]:
resampled_df.head()

,temperature_2m (°C),relative_humidity_2m (%),weather_code (wmo code),wind_speed_10m (km/h),wind_direction_10m (°),day,hour,electric-combined,electric-combined-yesterday,electric-combined-last-week,electric-combined_3H-forecast
time,,,,,,,,,,,
2017-09-01 00:00:00,10.465306,89.469388,0,8.348980,253.976190,4.0,0.0,9736.94,0.0,0.0,11199.00
2017-09-01 03:00:00,9.292857,91.877551,1,5.606803,236.513605,4.0,3.0,11199.00,0.0,0.0,18686.89
2017-09-01 06:00:00,11.101701,87.887755,3,3.805442,236.986395,4.0,6.0,18686.89,0.0,0.0,19569.85
2017-09-01 09:00:00,13.079252,81.112245,3,5.465986,159.707483,4.0,9.0,19569.85,0.0,0.0,16771.05
2017-09-01 12:00:00,14.598007,76.567821,2,8.024672,54.914829,4.0,12.0,16771.05,0.0,0.0,21973.35

In [35]:
resampled_df.to_csv('/Users/barry/CodeAcademy/Ideal_dataset/combined_houses/6_months_data_3H.csv')